In [1]:
import pandas as pd
import numpy as np
from functools import reduce
import os
import matplotlib.backends 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path         = '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix' 
files        = os.listdir(path)
results      = [os.path.join(path,i) for i in files if i.startswith('TCGA')]
results

['/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-KICH.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-BRCA.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-HNSC.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-PRAD.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-PAAD.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-ACC.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-LUAD.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-LUSC.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-KIRC.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-THCA.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-ESCA.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-KIRP.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-STAD.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-COAD.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-LIHC.tsv',
 '/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/TCGA-BLCA.tsv']

In [3]:
dfs =list()
for lncde in results:
    df   = pd.read_csv(lncde, sep='\t',header=0,skipinitialspace=True)
    dfs.append(df)
frame=pd.concat(dfs,axis=1)

In [4]:
refs        ='/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/Tcga_R/GDCdata/TCGA-BRCA/harmonized/Transcriptome_Profiling/Gene_Expression_Quantification/r_data/reference/Homo_sapiens.GRCh38.97.chr.txt'
ref         = pd.read_csv(refs, sep="\t", header=0,skipinitialspace=True)
lncRNAs_ref = ref.query('biotype == "lncRNA"')
PCs_ref =ref.query('biotype == "protein_coding"')
PCs_ref

              chr   start     end          gene_id    gene_sym         biotype
8               1   65419   71585  ENSG00000186092       OR4F5  protein_coding
27              1  450703  451697  ENSG00000284733      OR4F29  protein_coding
42              1  685679  686673  ENSG00000284662      OR4F16  protein_coding
60              1  923928  944581  ENSG00000187634      SAMD11  protein_coding
61              1  944203  959309  ENSG00000188976       NOC2L  protein_coding
...           ...     ...     ...              ...         ...             ...
60610  KI270726.1   26241   26534  ENSG00000277856  AC233755.2  protein_coding
60611  KI270726.1   41444   41876  ENSG00000275063  AC233755.1  protein_coding
60612  KI270711.1    4612   29626  ENSG00000271254  AC240274.1  protein_coding
60615  KI270713.1   31698   32528  ENSG00000277475  AC213203.2  protein_coding
60616  KI270713.1   35407   35916  ENSG00000268674  AC213203.1  protein_coding

[19986 rows x 6 columns]

In [5]:

## Change it into dataframe
dfs    = [pd.read_csv(x, sep='\t') for x in results]
merged = pd.concat(dfs, axis=1)
merged.reset_index(inplace=True)
merged.rename(columns={'index':'gene_id'},inplace=True)

In [ ]:
merge_lncRNAs = pd.merge(lncRNAs_ref[["gene_id","gene_sym"]],merged, on ='gene_id')

In [ ]:
merged_PC = pd.merge(PCs_ref[["gene_id","gene_sym"]],merged, on='gene_id')

In [16]:
merge_lncRNAs.head()

,gene_id,gene_sym,TCGA-KO-8416-01A-11R-2315-07,TCGA-KL-8327-01A-11R-2315-07,TCGA-KL-8343-01A-11R-2315-07,TCGA-KN-8434-01A-11R-2315-07,TCGA-KL-8342-01A-11R-2315-07,TCGA-KN-8428-01A-11R-2315-07,TCGA-KL-8336-01A-11R-2315-07,TCGA-KL-8329-01A-11R-2315-07,...,TCGA-GD-A2C5-11A-11R-A180-07,TCGA-BT-A20Q-11A-11R-A14Y-07,TCGA-GC-A6I3-11A-11R-A31N-07,TCGA-CU-A0YR-11A-13R-A10U-07,TCGA-BT-A20W-11A-11R-A14Y-07,TCGA-GC-A3WC-11A-11R-A22U-07,TCGA-BT-A20N-11A-11R-A14Y-07,TCGA-K4-A5RI-11A-11R-A28M-07,TCGA-GC-A3BM-11A-11R-A22U-07,TCGA-BT-A20U-11A-11R-A14Y-07
0,ENSG00000243485,MIR1302-2HG,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000237613,FAM138A,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000238009,AL627309.1,0,0,0,2,1,1,5,3,...,0,0,0,7,0,0,0,1,1,1
3,ENSG00000239945,AL627309.3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000239906,AL627309.2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,4

In [29]:
triplex_common_de_chr =pd.merge(triplex_common_de['gene_sym'],lncRNAs_ref, on='gene_sym')
chrcor =triplex_common_de_chr.drop_duplicates()
chrcor.to_csv('/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/de_lncRNAs_triplex_chr_cordinates', sep='\t',index=False)

In [30]:
triplex_common_de_chr

          gene_sym chr      start        end          gene_id biotype
0           SNHG12   1   28578538   28583132  ENSG00000197989  lncRNA
1    SLX1A-SULT1A3  16   30193892   30204310  ENSG00000213599  lncRNA
2    SLX1A-SULT1A3  16   30193892   30204310  ENSG00000213599  lncRNA
3    SLX1A-SULT1A3  16   30193892   30204310  ENSG00000213599  lncRNA
4    SLX1A-SULT1A3  16   30193892   30204310  ENSG00000213599  lncRNA
..             ...  ..        ...        ...              ...     ...
570     AC009163.6  16   75433836   75436392  ENSG00000274220  lncRNA
571     AC122719.1   5     946315     956520  ENSG00000248949  lncRNA
572     GRPEL2-AS1   5  149348116  149357642  ENSG00000253618  lncRNA
573     AC104316.2   8  122977026  122985629  ENSG00000259631  lncRNA
574      LINC01435  10  107694973  108197849  ENSG00000229981  lncRNA

[575 rows x 6 columns]

In [9]:
triplex_common_de = pd.read_csv('/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/de/common_de_lncRNAs_triplex', sep='\t',header=0)

In [17]:

triplex_common_de.rename(columns={'external_gene_name':'gene_sym'},inplace =True)

In [18]:
t=pd.merge(merge_lncRNAs,triplex_common_de['gene_sym'],on='gene_sym')

In [20]:
t.head()

,gene_id,gene_sym,TCGA-KO-8416-01A-11R-2315-07,TCGA-KL-8327-01A-11R-2315-07,TCGA-KL-8343-01A-11R-2315-07,TCGA-KN-8434-01A-11R-2315-07,TCGA-KL-8342-01A-11R-2315-07,TCGA-KN-8428-01A-11R-2315-07,TCGA-KL-8336-01A-11R-2315-07,TCGA-KL-8329-01A-11R-2315-07,...,TCGA-GD-A2C5-11A-11R-A180-07,TCGA-BT-A20Q-11A-11R-A14Y-07,TCGA-GC-A6I3-11A-11R-A31N-07,TCGA-CU-A0YR-11A-13R-A10U-07,TCGA-BT-A20W-11A-11R-A14Y-07,TCGA-GC-A3WC-11A-11R-A22U-07,TCGA-BT-A20N-11A-11R-A14Y-07,TCGA-K4-A5RI-11A-11R-A28M-07,TCGA-GC-A3BM-11A-11R-A22U-07,TCGA-BT-A20U-11A-11R-A14Y-07
0,ENSG00000225285,LINC01770,10,5,7,12,29,14,9,6,...,62,123,78,139,46,131,58,99,38,24
1,ENSG00000228526,MIR34AHG,1,0,0,1,1,0,0,2,...,3,1,5,2,5,2,1,5,7,3
2,ENSG00000224459,SLC25A34-AS1,3,6,2,12,6,2,2,2,...,1,0,17,1,7,0,3,7,0,4
3,ENSG00000197989,SNHG12,218,230,48,200,70,1465,165,118,...,319,123,1150,186,175,432,83,795,353,621
4,ENSG00000230615,AL139220.2,6,8,8,12,18,25,10,15,...,23,501,46,234,53,639,401,128,7,95

In [21]:
pd.merge(merge_lncRNAs,triplex_common_de['gene_sym'],on='gene_sym').to_csv('/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/df_lncRNAs_triplex', sep='\t',index=False)

In [ ]:
Triplex_genes_close_totripleDE_lncRNAs = pd.read_csv('/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/matrix/Genes_close_totriplex_delncRNAs',sep ='\t',header=0)
Triplex_genes_close_totripleDE_lncRNAs.head()
cis_triplex_DNA_lncRNAs                =Triplex_genes_close_totripleDE_lncRNAs.query('Distance<=100000')
lncRNAs=pd.DataFrame(Triplex_genes_close_totripleDE_lncRNAs['end'])
lncRNAs.reset_index(inplace =True)
lncRNAs.drop('index',inplace =True,axis=1)
lncRNAs.rename(columns={'end':'gene_sym'},inplace=True)

In [ ]:
PC=pd.DataFrame(Triplex_genes_close_totripleDE_lncRNAs['END'])
PC.reset_index(inplace =True)
PC.drop('index',inplace =True,axis=1)
PC.rename(columns={'END':'gene_sym'},inplace=True)

In [51]:
PC

    gene_sym
0     ATAD3B
1     ATAD3B
2     KLHL21
3     KLHL21
4      FHAD1
..       ...
504   NOTCH1
505    SNHG7
506     NXF3
507     NXF3
508     NXF3

[509 rows x 1 columns]

In [48]:
pd.merge(merge_lncRNAs,lncRNAs['gene_sym'],on='gene_sym').to_csv('/home/alva/Documents/lncRNAs_project_2020/Analysis_2021/DNA_methy_tcga/meth/de/de_lncRNAs_close_triplex_genes', sep='\t',index=False)